name: Firmware build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
        
        
permissions:
  contents: read

jobs:

  # Builds with DFU_UPDATE_BUILD=1        
  build_dfu:
    runs-on: ubuntu-20.04
    strategy:
      # devices to build for
      matrix:
        board: [PIXLJS]
      # try and build for all devices even if one fails
      fail-fast: false 
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        DFU_UPDATE_BUILD: 1
        BOARD: ${{ matrix.board }} 
        UPLOADTOKEN: ${{ secrets.UPLOADTOKEN }}  
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        make
        ./scripts/ci_upload.sh       
       
 
# Disable doc building for now 
#  docs:
#    runs-on: ubuntu-20.04      
#    steps:
#    - name: makedocs
#      run: make docs


